In [3]:
from scipy.io import loadmat
a = loadmat('/home/abian/Data/Dataset/IUMA/DermaDatabase/P13_C1000.mat')

In [7]:
a.keys()['']

dict_keys(['__header__', '__version__', '__globals__', 'calibratedHsCube', 'capture', 'dataResults', 'groundTruthMap', 'hsCube', 'imageGray', 'patient', 'preProcessedImage', 'spectralRGB', 'syntheticRGB'])

In [12]:
import numpy as np
np.unique(a['groundTruthMap'])

array([  0, 100, 402], dtype=uint16)

In [19]:
a['dataResults']['referenceClass']

array([[array([[array(['402'], dtype='<U3'), array(['Lesion'], dtype='<U6'),
                array(['Benign'], dtype='<U6'),
                array(['Basal_Cell_Carcinoma'], dtype='<U20'),
                array([[  0,   0, 255]], dtype=uint8)],
               [array(['100'], dtype='<U3'), array(['Skin'], dtype='<U4'),
                array(['Skin'], dtype='<U4'), array(['Skin'], dtype='<U4'),
                array([[  0, 255,   0]], dtype=uint8)]], dtype=object)      ]],
      dtype=object)

In [21]:
2**(116)-1

83076749736557242056487941267521535